server:
    port: 8080

spring:
    main:
        banner-mode: log
    mvc:
        servlet:
            path: /api
    data:
        mongodb:
            uri: mongodb+srv://${MONGODB_USER}:${MONGODB_PASS}@${MONGODB_HOST}/tico?retryWrites=true&w=majority
    servlet:
        multipart:
            max-file-size: 17MB
            max-request-size: 17MB

amazon:
    aws:
        accesskey: ${AMAZON_AWS_ACCESSKEY}
        secretkey: ${AMAZON_AWS_SECRETKEY}
        s3:
            region: ${AMAZON_AWS_S3_REGION}
            bucket: ${AMAZON_AWS_S3_BUCKET}
            cloudFront:
                domain: ${AMAZON_AWS_S3_CLOUD_FRONT_DOMAIN}
logging:
    file:
        path: logs/
        max-size: 16MB
        max-history: 256
        total-size-cap: 8GB

tico:
    users:
        sessions:
            ttl: 1800